FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

# no COPY . . here because we mount local folder via volumes

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]