version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:1@postgres:5432/mydb
      REDIS_HOST: redis
      DATA_DIR: /solidify/data
    volumes:
      - ./backend:/app
      - ./data:/solidify/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: